<?php require('template/header.phtml') ?>
<h3> Admin Page - Create User</h3>

<form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
    <div class="form-group">
        <label for="username" class="col-sm-3 control-label"> Username: </label>
        <div class="col-sm-4">
            <input type="text" class="form-control"  name="username" placeholder="enter username..." value="">
            <?php echo "<p class='text-danger'>$nameError</p>";?>
        </div>
    </div>

    <div class="form-group">
        <label for="password_1" class="col-sm-3 control-label"> Password: </label>
        <div class="col-sm-4">
            <input type="password" class="form-control"  name="password_1" placeholder="enter password..." value="">
            <?php echo "<p class='text-danger'>$password1Error</p>";?>
        </div>
    </div>

    <div class="form-group">
        <label for="password_2" class="col-sm-3 control-label"> Confirm Password: </label>
        <div class="col-sm-4">
            <input type="password" class="form-control"  name="password_2" placeholder="enter password..." value="">
            <?php echo "<p class='text-danger'>$password2Error</p>";?>
        </div>
    </div>

    <div class="form-group">

        <label for="usertype" class="col-sm-3 control-label"> User Type</label>
        <div class="col-sm-4">
            <select name="usertype" id="usertype">
                <option value=""></option>
                <option value="admin">Admin</option>
                <option value="user">User</option>

            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="email" class="col-sm-3 control-label"> Email: </label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="email" placeholder="enter email..." value="">
            <?php echo "<p class='text-danger'>$emailError</p>";?>
        </div>
    </div>


    <div class="form-group">
        <label for="address" class="col-sm-3 control-label"> Address: </label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="address" placeholder="enter address..." value="">
            <?php echo "<p class='text-danger'>$addressError</p>";?>
        </div>
    </div>

    <div class="form-group">
        <label for="phone" class="col-sm-3 control-label"> Phone: </label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="phone" placeholder="enter phone..." value="">
            <?php echo "<p class='text-danger'>$phoneError</p>";?>
        </div>
        <em><label id="format" class="col-sm-4 control-label">Format * E.g. 034-234-7890</label></em>
    </div>


    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-3">
            <input id="submit" name="create" type="submit" value="Create" class="btn btn-success">

            <input id="reset" name="reset" type="reset" value="Reset" class="btn btn-danger">
        </div>
    </div>
</form>



	
<?php require('template/footer.phtml') ?>
















