<?php require('template/header.phtml') ?>
<h2 id="lbl_Main" class="text-center"><u>Welcome to the Phone Adverts Website!</u></h2>

<div class="MainPicture">
    <img class="mainpics" src="images/1.jpg"/>
    <img class="mainpics" src="images/coolphones.jpg"/>
    <img class="mainpics" src="images/bluephone.jpeg"/>
    <img class="mainpics" src="images/vodafone.jpg"/>
</div>

<?php require('template/footer.phtml') ?>
