<?php require('template/header.phtml') ?>
<h2 id="lbl_Main" class="text-center"><u>Welcome to the Phone Adverts Website!</u></h2>

<div class="container-fluid MainPicture">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <img class="mainpics" src="images/1.jpg"/>
        </div>
        <div class="col-sm-12 col-md-6">
            <img class="mainpics" src="images/coolphones.jpg"/>
        </div>
        <div class="col-sm-12 col-md-6">
            <img class="mainpics" src="images/bluephone.jpeg"/>
        </div>
        <div class="col-sm-12 col-md-6">
            <img class="mainpics" src="images/SonyExperiaL1.png"/>
        </div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
