<?php require('template/header.phtml') ?>

    <h3> Locations Page </h3>


    <form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">

        <input type="text" id="searchcss" name="searchText" placeholder="Search for Locations..."/>

        <input type="Submit" id="searchcss" class="btn btn-success" name="searchLocButton" value="Search Locations"/>

    </form>

<br/>

    <style>
        #map{
            width: 1000px;
            height:680px;
        }
        @media screen  and (max-width:480px) {
            #map {
                width: 100%;
                height: 500px;
            }
        }
    </style>
<!---->
    <div id="usersLoc"></div>

    <div id="lat"></div>
    <div id="long"></div>
    <div id="map"></div>

<?php foreach ($view->LocationDataSet as $locationData){ ?>
    <?php echo  $locationData->getCity() ?>
    <script>

        if("geolocation" in navigator){
            navigator.geolocation.getCurrentPosition(function(position)
                {
                    currentlocation(position.coords.latitude,position.coords.longitude);
                }
            );
        }
        else
        {
            out.innerHTML = "no location";
        }


        function currentlocation(lat,long)
        {
            var out = document.getElementById("usersLoc");
            out.innerHTML = "Users Location: Latitude is currently " + lat + " , " + "Longitude is currently " + long;
        }

// center
        var map = new google.maps.Map(
            document.getElementById('map'),
            {
                zoom: 12, center: new google.maps.LatLng(<?php echo $locationData->getCenterLat() ?>, <?php echo $locationData->getCenterLong() ?>),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
        );

// dot location markers

        var infowindow = new google.maps.InfoWindow;
        var marker, i;

    </script>

<?php } ?>
    <?php foreach ($view->LocationDataSet as $locationData){ ?>
<script>


    for (i=0; i < 3; i++) {
            marker = new google.maps.Marker({
                position: new google.maps.LatLng(<?php echo $locationData->getLat() ?>, <?php echo $locationData->getLong() ?>), map: map
            });
// info window
            google.maps.event.addListener(marker, 'click', (function(marker, i) {
                return function() {
                    infowindow.setContent('<?php echo $locationData->getTitle() ?>'); /* just displays place name */
                    infowindow.open(map, marker);
                }
            })(marker, i));

            google.maps.event.addListener(marker, 'mouseout', (function (marker, i) {
                return function () {
                    infowindow.close();
                }
            })(marker, i));
        }
//
    </script>
<?php } ?>


    <div class="content">
        <h2>Your content would go here</h2>
    </div>


<?php require('template/footer.phtml') ?>