<?php require('template/header.phtml') ?>
<h3> Login Page </h3>
<?php


$first_num = rand(1, 10);
$second_num = rand(1, 10);

$operators = array("+", "-", "*");
$operator = rand(0, count($operators) - 1);
$operator = $operators[$operator];

$answer = 0;
switch($operator){
    case "+";
        $answer = $first_num + $second_num;
        break;
    case "-";
        $answer = $first_num - $second_num;
        break;
    case "*";
        $answer = $first_num * $second_num;
        break;
}
$_SESSION['answer'] = $answer;


?>

<form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
<div>
    <a href="register.php">Dont have an account! Register here!</a>
</div>
<br/>
    <div class="form-group">
        <label for="user" class="col-sm-2 control-label"> Username: </label>
        <div class="col-sm-4">
            <input type="text" class="form-control" id="name" name="user" placeholder="enter username..." value="">
            <?php echo "<p class='text-danger'>$usernameError</p>";?>
        </div>
    </div>

    <div class="form-group">
        <label for="pass" class="col-sm-2 control-label"> Password: </label>
        <div class="col-sm-4">
            <input type="password" class="form-control" id="pass" name="pass" placeholder="enter password..." value="">
            <?php echo "<p class='text-danger'>$passwordError</p>";?>
        </div>
    </div>

    <div class="form-group">
        <label for="captcha" class="col-sm-2 control-label"><?php echo $first_num . " " . $operator . " " . $second_num . " = "; ?> </label>
        <div class="col-sm-4">

            <input type="number" name="answer" />
            <?php echo "<p class='text-danger'>$captchaError</p>";?>
        </div>
    </div>



    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <input id="submit" name="login" type="submit" value="Login" class="btn btn-success">

            <input id="reset" name="reset" type="reset" value="Reset" class="btn btn-danger">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label><input value="check" name="check" type="checkbox"> Remember me? </label>
            </div>
        </div>
    </div>
<!---->
<!--    <div class="form-group">-->
<!--    <div class="col-sm-offset-2 col-sm-10">-->
<!--        <div>-->
<!--            <a href="changepassword.php">Change Password?</a>-->
<!--        </div>-->
<!--    </div>-->
<!--   </div>-->

</form>



<?php echo "<p class='text-danger'>$loginError</p>";?>
	
<?php require('template/footer.phtml') ?>
















