<?php require('template/header.phtml') ?>


<p> Paginate </p>

<?php foreach ($view->ProductspageDataSet as $productData){ ?>

    <form method="post" action="watchlist.php?action=add&id=<?php echo $productData->getId() ?>">

        <table class="table table-hover">
            <tr class="bg-active">
                <th>ID</th>
                <th>Image</th>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>

                <th></th>
            </tr>


            <tbody>
            <?php
            echo '<tr class="bg-danger"> <td class="text-info">' . $productData->getId() .
                '</td> <td >' . '<img src="images/' . $productData->getImage() . '" alt="no picture" height ="130" width="80px"/>' . '
            </td> <td>' . $productData->getTitle() . '</td>
            </td> <td class="text-danger">£' . $productData->getPrice() . '</td>
            <td class="text-danger">' . $productData->getfirstname() . '</td>
            <td> <input type="text" name="quantity" class="form-control" value="1" />
            <input type="hidden" name="hidden_name" value="' .  $productData->getTitle() . ' "/>
            <input type="hidden" name="hidden_price" value="' .  $productData->getPrice() . ' "/>
            <td><input type="submit" name="add_to_list" style="margin-top:5px;" class="btn-grad" value="Add to Watch List"/></td>
            </tr>';
            ?>
            </tbody>
        </table>


    </form>
<?php } ?>

<?php
$host = 'helios.csesalford.com';
$user = 'mvb620';
$pass = 'muffin11//';
$dbName = 'mvb620';

$con = mysqli_connect($host, $user, $pass, $dbName);

$results_per_page = 5; // 5 per page

$sql = "select phones.Title, userinfo.firstname
from phones
LEFT JOIN userinfo on phones.id = userinfo.userkey
";
$result = mysqli_query($con, $sql);
$number_of_results = mysqli_num_rows($result); // calculate no. of rows

$number_of_pages = ceil($number_of_results/$results_per_page); // no. of rows / 5

if(!isset($_GET['page'])) {
    $page = 1;
}else{
    $page = $_GET['page'];
}

//$this_page_first_result = ($page-1) * $results_per_page;

//$sql = "select * from phones LIMIT " . $this_page_first_result . ',' . $results_per_page;
//$result = mysqli_query($con, $sql);
//
while($row = mysqli_fetch_array($result)){
    echo $row['Title'] . ' ' . $row['firstname'] . '<br>';
}

?>

<ul class="pagination justify-content-center">
    <?php if($page <= 1){?>
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Previous</a></li><?php
    } else {
        echo '<li><a href="paginate.php?page=' . ($page - 1) . '">Prev</a></li>';
    } ?>
    <?php
for($pageloop=1;$pageloop<=$number_of_pages;$pageloop++) {
    echo '<li><a href="paginate.php?page=' . $pageloop . '">' . $pageloop . '</a></li>';
}
?>
    <?php if($page >= $number_of_pages){?>
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Next</a></li><?php
    } else {
        echo '<li><a href="paginate.php?page=' . ($page + 1) . '">Next</a></li>';
    } ?>

</ul>


<?php require('template/footer.phtml') ?>