<?php require('template/header.phtml') ?>

    <h3> Phones Page </h3>

    <?php
    if(isset($Loginname)) {
        echo "<h4 class='text-success'>Welcome $Loginname</h4>";
    }
    ?>

    <h2 id="phoneadvertstitle" class="text-center"><u>Welcome to the Phone Adverts page!</u> </h2>

    <form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">

        <input type="text" id="searchcss" name="searchtext" placeholder="Search for phones..." onkeyup="showHint(this.value)"/>

        <input type="Submit" id="searchcss" class="btn btn-danger" name="search" value="Search"/>

        <span class="glyphicon glyphicon-search" style="margin:5px"></span>

        <ul class="list-group" id="txtHint"></ul>

        <ul class="list-group" id="resultsSelectionBox">

        </ul>

    </form>

    <script>
        function showHint(str) {
            if (str.length == 0) {
                document.getElementById("txtHint").innerHTML = "";
                return;
            }
            else {
                var xmlhttp = new XMLHttpRequest();

                xmlhttp.onreadystatechange = function() {
                    if (this.readyState == 4 && this.status == 200) {
                        uic = document.getElementById("resultsSelectionBox");
                        var names = this.responseText.split(',');

                        for (var i = 0; i<names.length; i++){
                            var opt = document.createElement('option');
                            opt.value = names[i];
                            opt.innerHTML = names[i];
                            uic.appendChild(opt);
                        }

                        if (this.response != "no suggestions") {
                            uic.innerHTML = "Suggestions:<br/>";
                            var people = JSON.parse(this.responseText);
                            people.forEach(function (obj) {
                                uic.innerHTML += "<a href='productspage.php?id=" + obj.id + "'><img src='images/" + obj.image + "'>" +
                                    obj.name + ", Price: £" + obj.price + "</a><br/>";
                            });
                        }
                    }
                };

                xmlhttp.open("GET", "gethint.php?q=" + str, true);
                xmlhttp.send();
            }
        }
    </script>

    <div class="dropdown">

        <div class="btn-group">
            <button type="button" class="btn btn-danger">Sort By/Filters</button>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-header"><strong><i>Sort By</i></strong></li>
                <li><a class="dropdown-item" href="productspage.php?sort=lowToHigh">Lowest Price</a></li>
                <li><a class="dropdown-item" href="productspage.php?sort=highToLow">Highest Price</a></li>
                <li><a class="dropdown-item" href="productspage.php?sort=name(A-Z)">Name (A-Z)</a></li>
            </ul>
        </div>

        <div class="btn-group">
            <button type="button" class="btn btn-danger">Sort By Brand</button>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-header">Brand</li>
                <li><a class="dropdown-item" href="productspage.php?filter=apple">Apple</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=Samsung">Samsung</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=Sony">Sony</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=Nokia">Nokia</a></li>
            </ul>
        </div>

        <div class="btn-group">
            <button type="button" class="btn btn-danger">Sort By Price</button>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-header">Price</li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan50">Less than  £50</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan100">Less than £100</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan150">Less than £150</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan200">Less than £200</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan350">Less than £350</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan500">Less than £500</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=lessThan600">Less than £600</a></li>
            </ul>
        </div>

        <div class="btn-group">
            <button type="button" class="btn btn-danger">Sort By Colour</button>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li class="dropdown-header">Colour</li>
                <li><a class="dropdown-item" href="productspage.php?filter=blue">Blue</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=black">Black</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=white">White</a></li>
                <li><a class="dropdown-item" href="productspage.php?filter=grey">Grey</a></li>
            </ul>
        </div>
    </div>
    
    <div style="margin-top:30px;"></div>

    <div class="container-fluid">
        <div class="row">
            <?php foreach ($view->ProductspageDataSet as $productData){ ?>
                <div class="col-sm-3">
                    <form method="post" action="cart.php?id=<?php echo $productData->getId() ?>">
                        <img src="images/<?php echo $productData->getImage() ?>" style="height: 150px;" class="center">
                        <h5 class="text-center"><?php echo $productData->getTitle() ?></h5>
                        <h5 class="text-center">£<?php echo $productData->getPrice() ?></h5>
                        <input type="hidden" name="name" value="<?php echo $productData->getTitle() ?>">
                        <input type="hidden" name="price" value="<?php echo $productData->getPrice() ?>">
                        <input type="number" name="quantity" value="1" class="form-control">
                        <?php if(isset($_SESSION['logged_in']) && $_SESSION['logged_in']) { ?>
                            <input type="submit" name="add_to_cart" class="btn btn-warning btn-block my-2" value="Add To Cart">
                        <?php } ?>
                    </form>
                </div>
            <?php } ?>
        </div>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php
                for($i = 1; $i <= $total_pages; $i++){
                    echo "<li class='page-item'><a class='page-link' href='productspage.php?page=" . $i . "'>" . $i . "</a></li>";
            ?>
            <?php
                }
            ?>
        </ul>
    </nav>

    <div class="page-info">
        Showing  <?php echo $page ?> of <?php echo $total_pages; ?> pages
    </div>

<?php require('template/footer.phtml') ?>