<?php require('template/header.phtml') ?>


<p> More Info... </p>


    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Image</th>
                <th>Location</th>

                <th>Remove</th>


            </tr>

            <?php
            if(!empty($_SESSION["query"])) // if watch list session empty...
            {

                foreach($_SESSION["query"] as $keys => $values)  // uses foreach statement to loop through watch list session we created
                {
                    ?>
                    <tr>
                        <td><?php echo $values["Locid"]; ?></td>          <!-- uses key list to display each item from watch list session !-->
                        <td><?php echo $values["LocTitle"]; ?></td>
                        <td><img src="images/<?php echo $values["LocImage"]; ?>"></td>
                        <td><?php echo $values["LocName"]; ?></td>



                        <td><a href="querystring.php?action=delete&id=<?php echo $values["Locid"]; ?>"><span class="text-primary">Remove</span></a></td>

                    </tr>
                    <?php

                }

            }
            ?>
        </table>
    </div>











<?php require('template/footer.phtml') ?>