<?php require('template/header.phtml') ?>
    <h3> Payment Successful! </h3>

    <h4> Thank you for your payment feel free to explore more by using the back button or navbar links. </h4>

    <form class="form-horizontal" role="form" method="post" action="index.php">
        <div class="form-group">
            <div class="col-sm-4">
                <input id="back" name="adverts" type="submit" value="Back" class="btn btn-warning">
            </div>
        </div>
    </form>

<?php require('template/footer.phtml') ?>