<?php require('template/header.phtml') ?>
    <h3> Watch List </h3>


    <?php $number = 2 ?>

<form method="post" action="watchlist.php?action=add&id=<?php echo $number ?>">
    <input type="submit" name="add_to_watchlist" style="margin-top:5px;" class="btn-grad" value="Add to Watch List 1"/>
</form>

    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th width="40%">Item Name</th>
                <th width="10%">Quantity</th>
                <th width="20%">Price</th>
                <th width="15%">Total</th>
                <th width="5%"></th>
            </tr>

            <?php
            if(!empty($_SESSION["watch_list"])) // if watch list session empty...
            {
                $total = 0;
                foreach($_SESSION["watch_list"] as $keys => $values)  // uses foreach statement to loop through watch list session we created
                {
                    ?>
                    <tr>
                        <td><?php echo $values["item_name"]; ?></td>          <!-- uses key list to display each item from watch list session !-->
                        <td><?php echo $values["item_quantity"]; ?></td>
                        <td>£ <?php echo $values["item_price"]; ?></td>
                        <td>£ <?php echo number_format($values["item_quantity"] * $values["item_price"], 2); ?></td>
                        <td><a href="watchlist.php?action=delete&id=<?php echo $values["item_id"]; ?>"><span class="text-danger">Remove</span></a></td>
                    </tr>
                    <?php
                    $total = $total + ($values["item_quantity"] * $values["item_price"]);
                }
                ?>
                <tr>
                    <td colspan="3" align="right">Total</td>
                    <td align="right">£ <?php echo number_format($total, 2); ?></td>
                    <td></td>
                </tr>
                <?php
            }
            ?>
        </table>
    </div>






<form class="form-horizontal" role="form" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
    <div class="form-group">
        <div class="col-sm-4 ">
            <input id="back" name="adverts" type="submit" value="Back" class="btn btn-warning">
            <input id="logout" type="submit" name="logout" style="margin-top:5px;" class="btn btn-danger" value="Logout"/>
            <a href="postAdverts.php">Post Adverts?</a>
        </div>
    </div>
</form>





<?php require('template/footer.phtml') ?>