<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Bootstrap theme -->
    <!-- <link href="css/bootstrap.css" rel="stylesheet"> -->
    <!-- <link href="css/bootstrap-theme.css" rel="stylesheet"> -->
    <link href="css/my-style.css" rel="stylesheet">

    <title> E-commerce - (Server-Side Programming) - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.php">Ricks Website</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="productspage.php">Products</a>
                </li>
                <?php if(isset($_SESSION['logged_in']) && $_SESSION['logged_in']) {?>
                    <li class="nav-item">
                        <a class="nav-link" href="cart.php">Cart</a>
                    </li>
                <?php } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="register.php">
                        <i class="bi-person"></i> Sign Up
                    </a>
                </li>
                <?php if(isset($_SESSION['logged_in']) && $_SESSION['logged_in']) {?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="logout.php?q=logout">
                            <i class="bi-box-arrow-left"></i> Logout
                        </a>
                    </li>
                <?php } else { ?>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="login.php">
                            <i class="bi-box-arrow-right"></i> Login
                        </a>
                    </li>
                <?php } ?>

                <?php
                 if(!empty($_SESSION["cart"])) {
                    $cart_count = count(array_keys($_SESSION["cart"]));
                ?>
                    <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="cart.php">
                                <i class="bi-cart">
                                    <?php echo $cart_count; ?>
                                </i>
                            </a>
                    </li>
                <?php
                  }
                ?>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container">

    <div id="content">

